### ISSUE TITLE
Response time for queryMessages is too long

### ISSUE THREAD

**Issue by djohn17** [comapi/comapi-sdk-android#7]
When I invoke the queryMessages api, its noticed that response takes too long to return. Even I set a smaller limit, it still takes longer time when testing on devices.

**Comment by MarcinSwierczek** [comment]
Hi @djohn17, I'm getting querryMesssages rosponse times less than 100ms, also there is no additional processing of the response from server. The only bottleneck SDK side (apart from connection issues) could be the re-authentication process taking place at the same time. The query call will be queued in this case and executed, possibly with other queued requests after SDK receives a valid token.

To check for more details about what calls are being made and how long they take you can set a [logging](http://docs.comapi.com/reference#section-logging) configuration to comapi config object passed to [initialise](http://docs.comapi.com/reference#one-sdk-android-initialise) method:

`comapiConfig.logConfig(new LogConfig().setConsoleLevel(LogLevel.DEBUG).setNetworkLevel(LogLevel.DEBUG));`

**Comment by djohn17** [comment]
Hi @MarcinSwierczek , as per your suggestion I enabled the logging feature to see if any additional calls are being made and how long it takes. But it doesn't seem to make any additional calls. Please find below the console logs:

08-25 12:00:20.210 18300-18380/ D/OkHttp: <-- 200 OK https://api.comapi.com/apispaces/81ab6ac3-4133-4a9b-8140-266b57844b3f/conversations/8423bcd6-0f1a-4190-a8e8-fcb16c3e5f28/messages?limit=10 (1712ms)
08-25 12:00:20.210 18300-18380/ D/OkHttp: Server: nginx/1.11.6
08-25 12:00:20.210 18300-18380/ D/OkHttp: Date: Fri, 25 Aug 2017 00:00:22 GMT
08-25 12:00:20.210 18300-18380/ D/OkHttp: Content-Type: application/json; charset=utf-8
08-25 12:00:20.211 18300-18380/ D/OkHttp: Content-Length: 2060228
08-25 12:00:20.211 18300-18380/ D/OkHttp: Connection: keep-alive
08-25 12:00:20.211 18300-18380/ D/OkHttp: X-Powered-By: Express
08-25 12:00:20.211 18300-18380/ D/OkHttp: Access-Control-Allow-Origin: *
08-25 12:00:20.211 18300-18380/ D/OkHttp: Access-Control-Expose-Headers: ETag,Last-Modified
08-25 12:00:20.211 18300-18380/ D/OkHttp: ETag: W/"1f6fc4-eMhQIrWUgZIbdtgtd7l7DlZ6zGg"
08-25 12:00:40.789 18300-18380/ D/OkHttp: {"latestEventId":197,"earliestEventId":188,"messages"}

As you can see the response message with message information comes after 20 seconds of the request made.

**Comment by ben-moore** [comment]
Hi @djohn17, we've done some further investigation into this.  The underlying query executes in ~50ms however the conversation you are querying has several large images in the recent history which is causing a lot of data transfer on that particular call.  Our next service release includes changes that will optimise this scenario considerably.  

Just as a comparison, do you see better response times for other conversations?

**Comment by MarcinSwierczek** [comment]
Hi @djohn17, the v1.1.1 release of the SDK contains a new method in the messaging service - uploadContent(folder, contentData). You will find details on the docs [page](https://docs.comapi.com/reference#section-upload-content-data). This method allows you to upload the message attachments separately as a file, byte array or a base64 string. The response will return a full url to the data which you can put as an additional Part in a message you are sending. The combination of uploadContent and sendMessage APIs will solve the issue with long response times you are experiencing.
